const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
const UPDATE_COMMENT = 'UPDATE_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const UPDATE_POST = 'UPDATE_POST';
const SET_CURRENT_POST = 'SET_CURRENT_POST';

export { RECEIVE_CATEGORIES, RECEIVE_COMMENTS, UPDATE_COMMENT, DELETE_COMMENT, RECEIVE_POSTS, UPDATE_POST, SET_CURRENT_POST }
